apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-store-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DanielDeveloper19/Store_Management_KubernetesManifests.git
    targetRevision: HEAD
    path: storeManagement_chart/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: store-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true